/*
 * Copyright (C) 2018 CesarBianchi
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package sophiabcrypt.forms;

import com.thoughtworks.xstream.XStream;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import sophiabcrypt.SbcToLoad;
import sophiabcrypt.SbcVersion;

/**
 * This class is used to user select a prefered language for SophiaBCrypt
 * @author CesarBianchi
 * @since October/2018
 * @version 1.03.1
 * 
 */
public class SbcLanguageWindow extends javax.swing.JFrame {

    private String cLang = new String();
    private String cParamFileName = new String();
    
    /**
     * Creates new form SbcLanguageWindow
     * @author CesarBianchi
     * @since October/2018
     * @version 1.03.1
     */
    public SbcLanguageWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Selecione o Idioma:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portugues - Brasil (BR)", "English - United States (US)", "Spanish - Spain (ES)" }));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SbcLanguageWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SbcLanguageWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SbcLanguageWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SbcLanguageWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SbcLanguageWindow().setVisible(true);
            }
        });
    }
    /**
     * This method sets the cLang attribute by according user language choice using the local method
     * @author CesarBianchi
     * @since October/2018
     * @version 1.03.1
     * 
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (jComboBox1.getSelectedIndex() == 0 ){
            this.setLanguage("BR");
        } else if (jComboBox1.getSelectedIndex() == 1){
            this.setLanguage("EN");
        } else if (jComboBox1.getSelectedIndex() == 2){
            this.setLanguage("ES");
        }
        
        try {
            this.CreateParameterFile();
            
            SbcToLoad SbcLoad = new SbcToLoad();    
            SbcLoad.SetParamFileName(this.getParamFileName());
            if (SbcLoad.LoadParamFile()){  
                this.dispose();
                SbcLoad.LoadMainWindow();
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(SbcLanguageWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SbcLanguageWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

     /**
     * This method create a new parameter file and write it
     * @return lreturn True for succesfully file created or False for fail to create parameters file
     * @author CesarBianchi
     * @since October/2018
     * @version 1.03.1
     * 
    */
    private boolean CreateParameterFile() throws IOException{
        
        boolean lreturn = false;
        SbcVersion SbcVer = new SbcVersion();
        SbcVer.setLanguage(this.GetLanguage());
        
        XStream xstream = new XStream();
        
        
        Class<?>[] classes = new Class[] { SbcVersion.class };
        xstream.setupDefaultSecurity(xstream);
        xstream.allowTypes(classes);
        
        xstream.alias("Parameters",SbcVersion.class);
        String cXMLParams = xstream.toXML(SbcVer);
        
        FileWriter fw = new FileWriter(this.getParamFileName(), false);
        BufferedWriter bw = new BufferedWriter(fw);
        bw.write(cXMLParams);
        bw.close();
        fw.close();       
        System.out.println("Fechei o arquivo");
        lreturn = true;
        
        return lreturn;
    }

    /**
     * This method show the Window interface of this class
     * @author CesarBianchi
     * @since October/2018
     * @version 1.03.1
     * 
    */
    public void LoadLanguageWindow(){
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
    }
    
    /**
     * This method returns the language defined by user
     * @return The language defined by user in String Type
     * @author CesarBianchi
     * @since October/2018
     * @version 1.03.1
     * 
    */
    public String GetLanguage(){
        return cLang;
    }
    
    /**
     * This method sets the cLang attribute by according input parameter
     * @author CesarBianchi
     * @since October/2018
     * @version 1.03.1
     * 
    */
    private void setLanguage(String Language) {
        cLang = Language;
    }
    
    /**
     * This method sets the ParamFileName
     * @param cFileName The name of the file param
     * @author CesarBianchi
     * @since October/2018
     * @version 1.03.1
     * 
    */
    public void setParamFileName(String cFileName) {
        cParamFileName = cFileName;
    }
    
    /**
     * This method gets the ParamFileName
     * @return cParamFileName The name of the file param
     * @author CesarBianchi
     * @since October/2018
     * @version 1.03.1
     * 
    */
    private String getParamFileName() {
        return cParamFileName;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
