package sophiabcrypt;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author cesarbianchi
 */
public class SbcProgressWindow extends javax.swing.JFrame {
    private int nQtdFiles = 0;
    private String[] aFiles = null;
    private String cOper  = new String();    
    private String cPsw = new String();
    private JFileChooser jFile = null;
    
    
    /**
     * Creates new form SbcProgressWindow
     */
    public SbcProgressWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Processando arquivos...");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aguarde");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Thread t = new Thread(() -> {
                try {
                    transferFiles();
                } catch (Exception ex) {
                    Logger.getLogger(SbcProgressWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            });
            t.start();
        } catch (Exception ex) {
            Logger.getLogger(SbcProgressWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        jFile.updateUI();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SbcProgressWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SbcProgressWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SbcProgressWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SbcProgressWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SbcProgressWindow().setVisible(true);
            }
        });
    }

    public void init(int Max){
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setResizable(false);
        this.setProgressBarLength(Max);
        this.setAlwaysOnTop(true);
        this.setAutoRequestFocus(true);
        this.setVisible(true);
    }
    
    public void setProgressBarLength(int Max){
        this.jProgressBar1.setMaximum(Max);
    }
    
    public void incProc(String cMsg1, String cMsg2, int nStep) throws InterruptedException{
        
        jLabel1.setText(cMsg1);
        jLabel2.setText(cMsg2);
        jProgressBar1.setValue(nStep);        

        jLabel1.repaint();
        jLabel2.repaint();
        jPanel1.repaint();

        jLabel1.updateUI();
        jLabel2.updateUI();
        jPanel1.repaint();
        
    }
    
    public void setQtdFiles(int Qtd){
        nQtdFiles = Qtd;
    }
    
    public int getQtdFiles(){
        return nQtdFiles;
    }
    
    public void setFiles(String[] aF){
        aFiles = aF;
    }
    
    public String[] getFiles(){
        return aFiles;
    }
    
    public void setOper(String cOp){
        cOper = cOp;
    }
    
    public String getOper(){
        return cOper;
    }
    
    public void setPsw(String cPassword){
        cPsw = cPassword;
    }
    
    public String getPsw(){
        return cPsw;
    }
    
    public void transferFiles() throws Exception{
        
        String cOp = getOper();
        String[] aFl = getFiles();
        String cPassword = getPsw();
        
        //Define tamanho da regua de processamento
        this.jProgressBar1.setMaximum(getQtdFiles());
        
        //Instancia o motor de transformacao de arquivos
        SbcEncEngine SbcEngine = new SbcEncEngine();
        SbcEngine.setOper(cOp);
        SbcEngine.setFiles(aFl);
        SbcEngine.setQtdFiles(getQtdFiles());
        SbcEngine.setSbcExtension(".sbc");
        
        //Converte os arquivos
        for (int nI = 1; nI <= getQtdFiles();nI++){
            //Atualiza o rotulo
            String cMsg1 =  "Convertendo arquivo " + Integer.toString(nI) + " de " + Integer.toString(getQtdFiles());
            String cMsg2 =  aFl[nI];
            incProc(cMsg1,cMsg2,nI);
 
            //Converte o arquivo
            if (cOp == "ENC") {
                SbcEngine.GoCrypt(cPassword, aFl[nI]);
            }else{
                SbcEngine.GoDecrypt(cPassword, aFl[nI]);
            }
            
        }
        //jFile.updateUI();
        this.dispose();
            
    }
    
    public void setFileTreeObj(JFileChooser jF){
        jFile = jF;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
